[theme]
base = "dark"
primaryColor = "#FFA500"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "monospace"

[client]
toolbarMode = "minimal"
showErrorDetails = true
